### PR TITLE
update to 2.30.8

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by scribam** [comment]
Gentle ping @Macdu

**Comment by scribam** [comment]
No issues with Vita3K CI: https://github.com/scribam/Vita3K/actions/runs/11147591618

**Comment by Macdu** [comment]
Thanks for the ping. 
Do you really think it is worth it to update the repository only for a single minor update? (If you think it is I'll merge it).

**Comment by scribam** [comment]
@Macdu Here is the changelog, the fixes related to the first two lines would be nice to have:
- Fixed a crash in XInput code at startup
- Fixed flooding the OS with I/O when a PS4/PS5 controller is disconnected
- Added SDL_VIDEO_DOUBLE_BUFFER support to the Wayland backend
- SDL_WINDOWEVENT_EXPOSED is sent appropriately when using Wayland
- Fixed hang at startup in audio code when the application has large stack usage on Linux
- Fixed initializing KMSDRM on older Linux systems
- The pre-built SDL2.dll no longer depends on ucrtbase.dll

**Comment by Macdu** [comment]
Sure, if you think it is worth the update

**Pull request merged**
